#!/bin/sh

usage() {
cat<<EOF
Usage: ebk book_name
search book name in ~/ebk_dump/dump.txt
EOF
}

[ -z $1 ] && usage && exit

query="grep -i $1 ~/ebk_dump/dump.txt"
cmd_file='/tmp/ebk.tmp.sh'

shift

until [ -z $1 ]
do
  query="$query | grep -i $1"
  shift
done

echo $query > $cmd_file

sh $cmd_file

rm $cmd_file
