#!/usr/bin/env ruby

log_cmd = "git log --oneline --graph | cat -n"

if ARGV.empty?
  system(log_cmd + ' | less')
  exit
end

log = `#{log_cmd}`

line_no = ARGV.shift

before = after = nil

log.each_line do |l|
  l_arr = l.split
  no = l_arr[0]
  star = l_arr.index('*')
  next unless star
  id = l_arr[star.succ]
  if after
    before = id
    break
  end
  after = id if no == line_no
end

diff_cmd = "git diff #{before} #{after} --color"

system diff_cmd if before

puts diff_cmd
