#!/bin/env ruby

# get -name option for find

filename_pattern = nil

keys = []

until ARGV.empty?
  opt = ARGV.shift
  case opt
  when '-f'
    filename_pattern = " -name #{ARGV.shift} "
  when '-i'
    keys << "-i '#{ARGV.shift}' "
  else
    keys << "'#{opt}' "
  end
end

# check ARGV

if keys.empty?
  puts 'no argv 1'
  exit
end

# concat cmd

cmd="find -type f #{filename_pattern} | xargs egrep -H #{keys.shift}"

cmd += " | grep -E #{keys.shift}" until keys.empty?

# execute cmd

puts cmd unless system cmd