#!/bin/env ruby

# notice : if you want to pass backslash to grep, wrap it with quotes

# get -name option for find

filename_pattern = nil

keys = []

add_key = Proc.new do |k, op|
  if keys.empty?
    keys << "#{op} '#{k}' "
  else
    keys << "#{op} ':.*#{k}' "
  end
end

until ARGV.empty?
  opt = ARGV.shift
  case opt
  when '-f'
    filename_pattern = " -name #{ARGV.shift} "
  when '-i'
    add_key.call ARGV.shift, '-i'
  else
    add_key.call opt
  end
end

# check ARGV

if keys.empty?
  puts 'no argv 1'
  exit
end

# concat cmd

cmd="find -type f #{filename_pattern} | xargs egrep -H #{keys.shift}"

cmd += " | grep -E #{keys.shift}" until keys.empty?

# execute cmd

puts cmd unless system cmd