#!/bin/env ruby

def usage
  puts "Usage: headless -nNUM file1 file2 ...\nSomething like tail -n +NUM"
  exit
end

def ARGV.n
  return @n if @n
  input = []
  until empty?
    arg = shift
    if m = /-n(\d*)/.match(arg)
      @n = (m[1].empty? ? shift : m[1])
    else
      input << arg
    end
  end
  input.each{|inp| push inp}
  usage unless /^\d+$/.match @n
  @n = @n.to_i
end

class << ARGF
  def name
    f = self.file
    f.is_a?(File) ? f.path : 'stdin'
  end

  def another?
    @current ||= ARGF.file
    bool = @current != ARGF.file
    @current = ARGF.file
    bool
  end
end

output = Hash.new do |h, k|
  h[k] = []
end

def output.flush
  return values if keys.count == 1
  map do |file_name, lines|
    "==> #{file_name} <==\n#{lines.join}"    
  end.join("\n")
end

# main
ignore = ARGV.n

ARGF.each_line do |line|
  ignore = ARGV.n if ARGF.another?
  
  if ignore == 0
    output[ARGF.name] << line
  else
    ignore = ignore.pred
  end
end

puts output.flush
