#!/bin/sh

seq 50 \
  | while read f;do rake test 2>/dev/null;done \
  | grep Finish \
  | sort \
  | awk '{print $3}' \
  | sed 's/s,//' \
  | ruby -e 'samples = 60.times.map{gets.to_f}.sort; puts "#{samples}\n-----\n#{samples.slice(15, 30).sum / 30}"'
