#!/bin/sh

# cmd or plain src

if [ -e $1 ]
then
  src=$1
  filename=$(basename $1)
else
  src=$(which $1)
  filename=$1
fi

shift

# create a tmp src file, bring opts to it

tmpsrc="tmp.$$.rb"

echo "#!/usr/bin/env ruby" >$tmpsrc

while [ "$#" -gt 0 ]
do
  echo "ARGV.push '$1'"
  shift
done >>$tmpsrc

cat $src >>$tmpsrc

# profile

ruby-prof -p call_stack -f $filename.$(date +%Y%m%d-%H%M%S).html $tmpsrc

# clean

rm $tmpsrc